### ISSUE TITLE
No way of stoping the Disco Animation

### ISSUE THREAD

**Issue by franco-101** [RaimondB/node-red-contrib-daylight-rgbw#188]
Hello
I am struggling to stop the Disco Animation once its started, is there something I can send to the node to make it stop?
Thanks
Francis

**Comment by RaimondB** [comment]
Hi, it seems I have not clearly documented this, I will improve the documentation on that.
The solution is simple, just send a payload containing "STOP".

Although, I now think it might be more logical to accept "OFF" as well to automatically work together with switch based inputs.

![image](https://user-images.githubusercontent.com/12556944/100321955-cc70ba00-2fc3-11eb-8a8a-7eabbdbb9965.png)

**Comment by franco-101** [comment]
Some switches also use Payload.On set to False, could you include True and False Boolean, aswell as ON and OFF?

**Comment by RaimondB** [comment]
> Some switches also use Payload.On set to False, could you include True and False Boolean, as well as ON and OFF?

Do you have an example of nodes that work this way? Because I think it is useful to support widely used standards out of the box, but supporting al variations is something why also Function and Switch nodes exist, so that you can do the translation yourself.

Personally I am using Openhab for most of my devices, so that is what I normally test with.
